name: Release Notifier
description: "Notify Slack about your releases without spamming the channel"
inputs:
  gitHubApiToken:
    description: the token for GitHub API calls for releases
    required: true
  slackApiToken:
    description: the token for Slack API calls for message search and posting
    required: true
  slackChannelId:
    description: the Slack channel ID where the posts go
    required: true
runs:
  using: "composite"
  steps:
    - name: store activity
      run: export GH_EVENT_ACTIVITY="${{ github.event.action }}"
      shell: sh
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15.0'
    - name: run code
      run: go run ./cmd/notifier