name: Release Notifier
description: "Notify Slack about your releases without spamming the channel"
inputs:
  GH_API_TOKEN:
    description: the token for GitHub API calls for releases
    required: true
  SLACK_API_TOKEN:
    description: the token for Slack API calls for message search and posting
    required: true
  SLACK_CHANNEL_ID:
    description: the Slack channel ID where the posts go
    required: true
runs:
  using: "composite"
  steps:
    - name: store activity
      run: export GH_EVENT_ACTIVITY="${{ github.event.action }}"
      shell: sh